### ISSUE TITLE
Connection reach max issue

### ISSUE THREAD

**Issue by gohsianghwee** [orientechnologies/OrientDB-NET.binary#66] opened 2015-04-22 02:44 UTC
Hi,

I always encounter connection reach max issues whereby I have ensured the connection has been closed for each usage by using the "using" keywords in c#. Below is the sample code,

 using (var database = new ODatabase(databaseName))
            {
                // logic is here
            }

I even tried to close the server connection each time by calling Server.Close(). It happens occasionally for the unit test cases. but it is alright sometime. But when it go to production testing, it always crash. Am I doing something wrong? 

Thanks.
Cordially,
Goh

**Comment by GoorMoon** [comment] 2015-04-24 16:35
@gohsianghwee 
Just checked DatabasePool and it's work correctly.
How you create DatabasePool and Destroy it ?

**Comment by thiagopm** [comment] 2015-05-14 18:04
Hi
I have a problem like this after a hour that I turn on my Sync Service (update OrientDB from a queue of tasks):

On the client I get the error:
"Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream."

On the server this:
"2015-05-14 12:57:08:151 WARNING Reached maximum number of concurrent connections (1001), reject incoming connection from /10.0.11.128:4956 [OServerNetworkListener]"

I have 3 queues and one thread for each. When I Start a thread I Create a connectionPool.

I'm not Destroying the pool. Should I?

When I see the connections on server, there is a a lot of  "CLOSE_WAIT" status like this:
TCP    10.0.1.15:2424         10.0.21.221:5485       CLOSE_WAIT
TCP    10.0.1.15:2424         10.0.21.221:5497       CLOSE_WAIT

The OrientDB process keep this connection opened there?

Thanks in advance,
Thiago

**Comment by GoorMoon** [comment] 2015-05-14 19:03
@thiagopm,
Can you please provide minimal example of issue.
From your description i understand that driver not close connections.
But in my test case can't reproduce this.

**Comment by thiagopm** [comment] 2015-05-14 20:54
@GoorMoon,

I'll do it, but one more question.

We are using a distributed environment (3 server instances balanced by AWS elastic load balance)

Have you ever tested in this kind of environment?

When closing the connection, how the API knows what the connection server was opened?

thanks,
Thiago

**Comment by GoorMoon** [comment] 2015-05-19 14:04
@thiagopm,
I never tested Driver in the distributed environment.
Driver manage Connection in the OConnection class and close it then class disposed.

**Closed** 2016-06-21 13:56 UTC
Labels: bug
